### ISSUE TITLE
TB version 102 102.0b8 - Folder Properties window truncated

### ISSUE THREAD

**Issue by BillH99999** [Welpy-cw/Folder-Account#12]
Just thought you might want to know as version 102 of TB is being released next week as I understand it.

In version 102 of Thunderbird, Folder-Account is causing a truncation on the bottom of the Folder Properties window.  The OK and Cancel buttons are being truncated.  If I disable the add-on they display correctly.

![Folder Properties display problem](https://user-images.githubusercontent.com/26846819/175348346-3d3c9d43-0f1c-4335-96d1-316dffe6a56a.jpg)

Thanks,
Bill

**Comment by BillH99999** [comment]
I just noticed in another issue that there is a pre-release version available.  I downloaded version 11.3 and installed it.  I am still getting the same truncation in TB 102.0b8.

Thanks,
Bill

**Comment by Welpy-cw** [comment]
@BillH99999 Thank you for your report. I missed this because most of my folders on my Windows installation don't show the "When getting new messages for this account, always check this folder" line.

Apparently TB102 for Windows _does_ correctly resize the dialog itself, while under Linux the dialog gets truncated on the right side. So I limited my original fix to Linux. Unfortunately I don't know how it gets displayed on Mac installations.

I just published a new [pre-release version](https://github.com/Welpy-cw/Folder-Account/releases) containing this fix and some other changes, feel free to check it out.

**Comment by BillH99999** [comment]
Thanks for the quick reply and fix.  I can confirm that with this new version the problem is corrected.

Thanks,
Bill

**Comment by BillH99999** [comment]
@Welpy-cw 
Just curious... will version 11.3 be available in the add-on "store"?
Thanks,
Bill

**Comment by Welpy-cw** [comment]
@BillH99999 Yes, that's the plan at least. Would you care to install the latest [pre-release version](https://github.com/Welpy-cw/Folder-Account/releases) and give some feedback? I'm still a bit hesitant because of the modified archive function, the moved options and some internal changes ...

**Comment by BillH99999** [comment]
I have been using pre-release 2 since yesterday and didn't have any problems or see anything odd.  I will keep an eye on pre-release 4.  I may not be the best test bed for you as I only use the "From Account"  and "Default To" options.
Thanks,
Bill

**Comment by Welpy-cw** [comment]
This has been a [Thunderbird bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1778958), which has been fixed in TB 102.1. Workaround has been removed, closing issue.
