### ISSUE TITLE
not compatible with TB 128 esr

### ISSUE THREAD

**Issue by BillH99999** [Welpy-cw/Folder-Account#19]
Folder-Account is flagged as not compatible with TB 128 esr.  It would be great if you could update it for TB 128 esr.

Thanks,
Bill

**Comment by moonlitbugs** [comment]
Note that the Mozilla Extensions repository has version **12.0** released on *June 12* that fixes this for TB *128esr*.  Thus, this issue probably should have been closed at that time.  However, the most recent release as of today (*Aug 9*) is **11.3.2**?  And the most recent pre-release is *12.0-beta3*?  Are we missing a code update not in GitHub?

Also, and the reason I came here today, is that we need *yet another* update, this time for TB **129.0**.  Tacking that onto this issue as the issue is still open.

**Comment by Welpy-cw** [comment]
@BillH99999 @moonlitbugs Thanks for your comments. Version 12.0 is identical to 12.0b3 and has been available for ESR 128 for quite some time. I just set the max version to 131.* on [ATN](https://addons.thunderbird.net/de/thunderbird/addon/folder-account/versions/). Please report back if there are still any problems, thank you!

**Comment by BillH99999** [comment]
It was version 12.0 that was flagged as incompatible in my TB 128 installation.

Sorry, I can't test now since I reverted to TB 115 due to the corruption issues in TB 128.

Edit:  Sorry, I think this is wrong.  I think version 12.0 did work for me in TB 128.  I was thinking of a different add-on.  Sorry about that and thanks for the great add-on and the update for TB 128.

**Comment by moonlitbugs** [comment]
Thanks, @Welpy-cw I am now enjoying **TB 129** :smiley: 

This is such a useful add-on.  Ought to be incorporated upstream.
