### ISSUE TITLE
Cursor positionning when replying

### ISSUE THREAD

**Issue by f6fvy** [Welpy-cw/Folder-Account#9]
Hi

I'm using Folder Account 11.1 with TB 91.3 (windows).

Since the release of the new version 91 of TB, when replying to an email located in a local folder, *sometimes* the cursor is positioned after the recipient email address, instead of the text body. It seems to happen more with mailing-lists. This strange behavior doesn't exist when I disable this Folder-Account extension.

Any idea ?

**Comment by Welpy-cw** [comment]
@f6fvy See issue #8, which has already been closed by the reporter. Causing this behavior is a bug in Thunderbird, that recently has been fixed in the development version and hopefully will be backported to the next release (91.4).

For the time being you could install the pre-release version 11.1.1 from this site, which contains a workaround for the issue.

**Comment by f6fvy** [comment]
Thank you for your reply. I will install 11.1.1.
